[package]
name = "mainspring"
version = "0.2.2"
authors = ["Nate Catelli <ncatelli@packetfire.org>"]
edition = "2021"

[dependencies.isa-mos6502]
git = "https://github.com/ncatelli/isa-mos6502"
tag = "v1.1.0"
default-features = false
features = []
