name: Release
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  release:
    name: Release
    environment: manual-release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
      - name: Add release deps
        run: cargo install 'cargo-edit@0.12.0'
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
      - name: Install dependencies
        run: npm install --save-dev semantic-release @semantic-release/git @semantic-release/changelog @semantic-release/exec
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release